config/routes.rb
Rails.application.routes.draw do

  root to: 'logins#new'

  resources :users
  resources :piggy_banks do
    resource :movements
  end

  get '/', to: 'logins#new', as: 'new_login'
  post '/login', to: 'logins#create', as: 'create_login'
  get '/logout', to: 'logins#destroy', as: 'destroy_login'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/movement.rb
class Movement < ApplicationRecord
  before_save     :increase_piggy_bank
  before_destroy  :decrease_piggy_bank

  belongs_to      :piggy_bank

  private
  def increase_piggy_bank
    piggy_bank.on_movement_create(amount)
  end

  def decrease_piggy_bank
    piggy_bank.on_movement_destroy(amount)
  end

end

app/models/piggy_bank.rb
class PiggyBank < ApplicationRecord
  before_create :update_total_values
  belongs_to :user

  def update_total_values
    if self.balance.positive?
      self.total_credit += balance
    else
      self.total_debit += balance.abs
    end
  end

  def on_movement_create(amount)
    self.balance += amount
    if amount.positive?
      self.total_credit += amount
    else
      self.total_debit  += amount.abs
    end
    self.save
  end

  def on_movement_destroy(amount)
    self.balance -= amount
    if amount.positive?
      self.total_credit -= amount
    else
      self.total_debit  -= amount.abs
    end
    self.save
  end

end

app/models/summary.rb
class Summary
  attr_accessor :sum_of_balance, :sum_of_credit, :sum_of_debit

  def self.build_from_piggy_banks(piggy_banks)
    Summary.new.tap do |summary|
      summary.sum_of_balance = piggy_banks.inject(0){ |sum, pb| sum + pb.balance }
      summary.sum_of_credit = piggy_banks.inject(0){ |sum, pb| sum + pb.total_credit }
      summary.sum_of_debit = piggy_banks.inject(0){ |sum, pb| sum + pb.total_debit }
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  validates_uniqueness_of :email
  validates :email, format: { with: /\A.+@.+\Z/ }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery unless: -> { request.format.json? }

  rescue_from ActionController::ParameterMissing do |exception|
    render json: { message: exception.message, params: [exception.param] }, status: :bad_request
  end

  rescue_from ActiveRecord::RecordNotFound do |exception|
    respond_to do |format|
      format.html { render file: "errors/404", status: :not_found }
      format.json { render json: { message: exception.message }, status: :not_found }
    end
  end

  rescue_from ActiveRecord::RecordInvalid do |exception|
    respond_to do |format|
      format.html { flash.notice = exception.message; redirect_to request.referrer }
      format.json { render json: { message: exception.message }, status: :bad_request }
    end
  end

  before_action :set_locale
  before_action :verify_login

  def set_locale
    session[:locale] = params[:locale] || I18n.default_locale
    I18n.locale = session[:locale]
  end

  def default_url_options
    { locale: session[:locale] }
  end

  def verify_login
    redirect_to root_path unless request.format.json? || session[:user_id].present?
  end

  def current_user
    case request.format
    when Mime[:json]
      @user ||= authenticate_user
    else
      @user ||= User.find(session[:user_id]) if session[:user_id]
    end
  end

  private
  def authenticate_user
    authenticate_with_http_basic do |email, password|
      user = User.find_by!(email: email)
      return user if user.present? && user.authenticate(password)
    end
  end

end

app/controllers/logins_controller.rb
class LoginsController < ApplicationController

  skip_before_action :verify_login

  def index
  end

  def create
    user = User.find_by(email: params[:login][:email])
    if user.present? && user.authenticate(params[:login][:password])
      session[:user_id] = user.id
      redirect_to piggy_banks_path
    else
      flash.notice = "Email or Password invalid. Please try again"
      redirect_to root_path
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end

end

app/controllers/movements_controller.rb
class MovementsController < ApplicationController

  def create
    params.require(:piggy_banks_movement).permit!

    @movement = Movement.new(params[:piggy_banks_movement])
    @movement.piggy_bank_id = params[:piggy_bank_id]
    @movement.save

    respond_to do |format|
      format.html { redirect_to request.referrer }
      format.json { render json: { piggy_bank: @movement.piggy_bank, movement: @movement }, except: [:user_id], status: :created }
    end
  end

  def show
    @piggy_bank = PiggyBank.find_by!(user_id: current_user.id, id: params[:piggy_bank_id])
    @movements = Movement.where(piggy_bank_id: params[:piggy_bank_id]).order(updated_at: :desc)

    respond_to do |format|
      format.html { }
      format.json { render json: { piggy_bank: @piggy_bank, movements: @movements }, except: [:user_id, :piggy_bank_id], status: :ok }
    end
  end

  def destroy
    @movement = Movement.joins(:piggy_bank).find_by!('piggy_banks.id': params[:piggy_bank_id], 'piggy_banks.user': current_user.id, 'movements.id': params[:id])
    @movement.destroy

    respond_to do |format|
      format.html { redirect_to request.referrer }
      format.json { render json: "Movement deleted", status: :ok }
    end
  end

end

app/controllers/piggy_banks_controller.rb
class PiggyBanksController < ApplicationController
  def index
    @piggy_banks = PiggyBank.where(user_id: current_user.id).order(updated_at: :desc)
    @summary = Summary.build_from_piggy_banks(@piggy_banks)

    respond_to do |format|
      format.html
      format.json { render json: { summary: @summary, piggy_banks: @piggy_banks }, except: :user_id, status: :ok }
    end
  end

  def create
    params.require(:piggy_bank).permit!
    @piggy_bank = PiggyBank.new(params[:piggy_bank])
    @piggy_bank.user_id = current_user.id
    @piggy_bank.save

    respond_to do |format|
      format.html { redirect_to piggy_banks_path }
      format.json { render json: @piggy_bank, except: :user_id, status: :created }
    end
  end

  def edit
    @piggy_bank = PiggyBank.find_by!(id: params[:id], user_id: current_user.id)
  end

  def update
    params.require(:piggy_bank).permit!
    @piggy_bank = PiggyBank.where(user_id: current_user.id).update(params[:id], params[:piggy_bank])

    respond_to do |format|
      format.html { redirect_to piggy_banks_path }
      format.json { render json: @piggy_bank, except: :user_id, status: :ok }
    end
  end

  def destroy
    @piggy_bank = PiggyBank.find_by!(id: params[:id], user_id: current_user.id)
    @piggy_bank.destroy

    respond_to do |format|
      format.html { redirect_to piggy_banks_path }
      format.json { render json: "Piggy Bank deleted", status: :ok }
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  skip_before_action :verify_login

  def create
    params.require(:user).permit!

    user = User.new(params[:user])
    user.save!

    respond_to do |format|
      format.html do
        session[:user_id] = user.id
        redirect_to piggy_banks_path
      end
      format.json { render json: user, except: [:id, :password_digest], status: :created }
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/logins_helper.rb
module LoginsHelper
end

app/helpers/movements_helper.rb
module MovementsHelper
end

app/helpers/piggy_banks_helper.rb
module PiggyBanksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Piggy•B</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <%= favicon_link_tag 'favicon.ico' %>
    <%= favicon_link_tag 'piggy_bank_180.jpg', rel: 'apple-touch-icon', sizes: '180x180' %>
    <%= favicon_link_tag 'piggy_bank_152.jpg', rel: 'apple-touch-icon', sizes: '152x152' %>
    <%= favicon_link_tag 'piggy_bank_120.jpg', rel: 'apple-touch-icon', sizes: '120x120' %>
    <%= favicon_link_tag 'piggy_bank_76.jpg', rel: 'apple-touch-icon', sizes: '76x76' %>
    <%= favicon_link_tag 'piggy_bank_60.jpg', rel: 'apple-touch-icon', sizes: '60x60' %>
    <%= favicon_link_tag 'piggy_bank.png', rel: 'apple-touch-icon' %>
    <%= favicon_link_tag 'piggy_bank.png', rel: 'icon' %>

    <meta charset="UTF-8"> <meta name=viewport content="width=device-width, initial-scale=1">
  </head>

  <body>

    <header>
      <nav class="navbar fixed-top navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
          <% unless session[:user_id].blank? %>
            <%= link_to piggy_banks_path, class: "navbar-brand text-white" do %><%= image_tag "piggy_bank_white.png", class: "fixed-small-size" %> <b>Piggy</b>•B</a><% end %>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarOptions" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarOptions">
              <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                  <%= link_to t('.my_piggy_banks'), piggy_banks_path, class: "nav-link btn-sm mt-1 mb-1" %>
                </li>
                <li class="nav-item">
                  <%= link_to t('.create_piggy_bank'), new_piggy_bank_path, class: "nav-link btn-sm mt-1 mb-1" %>
                </li>
                <li class="nav-item">
                  <%= link_to t('.check_api_documentation'), 'https://goo.gl/3bFqXL', class: "nav-link btn-sm mt-1 mb-1", target: "_blank" %>
                </li>
              </ul>
              <span class="navbat-text">
                <%= link_to t('.logout'), '/logout', class: "btn mt-1 mb-1 btn-sm btn-block btn-outline-secondary" %>
              </span>
            </div>
          <% end %>
        </div>
      </nav>
    </header>

    <main>
      <%= yield %>
    </main>

    <footer class="footer">
        <b><small><%= t '.developed_by' %> <a href="http://gabrielqueiroz.github.io" target="_blank">Gabriel Queiroz</a> - 2018</small></b>
        <p><small><a href='?locale=en'>en</a> - <a href='?locale=pt-BR'>pt-BR</a></small></p>
    </footer>

  </body>
</html>

app/views/logins/new.html.erb
<div class="container">
  <h1 class="text-center"><b>Piggy</b>•B</h1>
</div>

<div class="container pt-3">
  <div class="row">
    <div class="col-md mb-2 text-center">
      <div class="card fill-height shadow-sm">
        <div class="card-body">
          <%= image_tag "piggy_bank.gif", class: "fill-width" %>
          <p class="text-muted mt-4">
            <%= t '.description_1' %>
          </p>
          <p class="text-muted mt-4">
            <%= t '.description_2' %>
          </p>
        </div>
      </div>
    </div>

    <div class="col-md mb-2">
        <% if flash[:notice] %>
          <div class="alert alert-danger" role="alert"> <%= flash.notice() %> </div>
        <% end %>

        <div class="card shadow">
          <div class="card-body">

            <%= form_with scope: :login, url: '/login' do |form| %>
              <div class="form-group">
                <%= form.text_field :email, class: "form-control", placeholder: "email", required: true %>
              </div>
              <div class="form-group">
                <%= form.text_field :password, class: "form-control", type: "password", placeholder: t('.password'), required: true %>
              </div>

              <%= form.submit t('.sign_in'), class: "btn btn-primary btn-block" %>
            <% end %>
          </div>
        </div>
        <hr /><small class="form-text text-muted text-center"><%= t '.signup_help' %></small>
        <div class="card shadow mt-2">
          <div class="card-body">
            <%= form_with scope: :user, url: users_path do |form| %>
              <div class="form-group">
                <%= form.text_field :name, class: "form-control", placeholder: t('.name'), required: true %>
              </div>
              <div class="form-group">
                <%= form.text_field :email, class: "form-control", placeholder: "email", required: true  %>
                <small id="emailHelp" class="form-text text-muted"><%= t '.password_help' %></small>
              </div>
              <div class="form-group">
                <%= form.text_field :password, class: "form-control", type: "password", placeholder: t('.password'), required: true  %>
              </div>
              <div class="form-group">
                <%= form.text_field :password_confirmation, class: "form-control", type: "password", placeholder: t('.confirm_password'), required: true  %>
              </div>

              <%= form.submit t('.sign_up'), class: "btn btn-success btn-block" %>
            <% end %>
          </div>
      </div>
    </div>
  </div>

</div>

app/views/movements/show.html.erb
<div class="container mt-5">
  <div class="row">
    <div class="col-md-6">
        <h3><%= t '.movements' %> <b><%= @piggy_bank.name %></b></h3>
    </div>
  </div>
</div>

<div class="container">
  <div class="row">
    <div class="col-md-6">
      <hr />
      <h5><%= t '.piggy_bank_details' %></h5>
      <div class="card mb-4 shadow">
        <div class="card-body">
          <%= render partial: "piggy_banks/piggy_bank_details", locals: { piggy_bank: @piggy_bank } %>
        </div>
      </div>
      <hr />
      <h5><%= t '.create_movement' %></h5>
      <div class="card mb-4 shadow">
        <div class="card-body">
          <%= form_with scope: :piggy_banks_movement, url: piggy_bank_movements_path do |form| %>
            <div class="form-group">
              <%= form.text_field :name, class: "form-control", placeholder: t('.name'), required: true %>
            </div>
            <div class="form-group">
              <%= form.text_field :description, class: "form-control", placeholder: t('.description'), value: ""  %>
            </div>
            <div class="form-group">
              <div class="btn-group btn-group-justified w-100" role="group">
                <button type="button" class="mov-button btn text-danger border-danger w-100">-5</button>
                <button type="button" class="mov-button btn text-danger border-danger w-100">-10</button>
                <button type="button" class="mov-button btn text-success border-success w-100">+5</button>
                <button type="button" class="mov-button btn text-success border-success w-100">+10</button>
              </div>
            </div>
            <div class="form-group">
              <%= form.text_field :amount, id: "mov-value", class: "form-control", value: "0.0", type: "number", step: ".01", required: true  %>
            </div>

            <%= form.submit t('.make_movement'), class: "btn btn-primary btn-block" %>
          <% end %>
        </div>
      </div>
    </div>

    <div class="col-md-6">
      <hr />
      <h5><%= t '.piggy_bank_movements' %></h5>
      <% if @movements.blank? %>
        <p><%= t '.help_1' %></p>
        <p><%= t '.help_2' %></p>
        <div class="card border-danger mb-4">
          <div class="card-body text-danger">
            <%= t('.help_3').html_safe %>
          </div>
        </div>
      <% else %>
        <% @movements.each do |mv| %>
            <div class="card shadow mb-4">
              <div class="card-body">
                <div class="row">
                  <div class="col-xl-4">
                    <%= @piggy_bank.currency %> <h2><%= number_to_currency mv.amount %></h2>
                  </div>
                  <div class="col-xl-6">
                    <h5 class="card-title"><%= mv.name %></h5>
                    <h6 class="card-subtitle mb-2 text-muted"><%= mv.description %></h6>
                    <h6> <%= mv.created_at.strftime("%m/%d/%Y at %I:%M%p") %> </h6>
                  </div>
                  <div class="col-xl-2 mt-2 small">
                    <%= link_to t('.destroy'), piggy_bank_movements_path(id: mv.id), method: :delete, data: { confirm: "Destroy movement #{mv.name}?" }, class: "card-link"%>
                  </div>
                </div>
              </div>
            </div>
        <% end %>
      <% end %>
  </div>
</div>

app/views/piggy_banks/_currencies.html.erb
<option value="CAD" selected="selected">CAD</option>
<option value="USD">USD</option>
<option value="BRL">BRL</option>
<option value="AED">AED</option>
<option value="AFN">AFN</option>
<option value="ALL">ALL</option>
<option value="AMD">AMD</option>
<option value="ANG">ANG</option>
<option value="AOA">AOA</option>
<option value="ARS">ARS</option>
<option value="AUD">AUD</option>
<option value="AWG">AWG</option>
<option value="AZN">AZN</option>
<option value="BAM">BAM</option>
<option value="BBD">BBD</option>
<option value="BDT">BDT</option>
<option value="BGN">BGN</option>
<option value="BHD">BHD</option>
<option value="BIF">BIF</option>
<option value="BMD">BMD</option>
<option value="BND">BND</option>
<option value="BOB">BOB</option>
<option value="BSD">BSD</option>
<option value="BTN">BTN</option>
<option value="BWP">BWP</option>
<option value="BYN">BYN</option>
<option value="BZD">BZD</option>
<option value="CDF">CDF</option>
<option value="CHF">CHF</option>
<option value="CLP">CLP</option>
<option value="CNY">CNY</option>
<option value="COP">COP</option>
<option value="CRC">CRC</option>
<option value="CUC">CUC</option>
<option value="CUP">CUP</option>
<option value="CVE">CVE</option>
<option value="CZK">CZK</option>
<option value="DJF">DJF</option>
<option value="DKK">DKK</option>
<option value="DOP">DOP</option>
<option value="DZD">DZD</option>
<option value="EGP">EGP</option>
<option value="ERN">ERN</option>
<option value="ETB">ETB</option>
<option value="EUR">EUR</option>
<option value="FJD">FJD</option>
<option value="FKP">FKP</option>
<option value="GBP">GBP</option>
<option value="GEL">GEL</option>
<option value="GGP">GGP</option>
<option value="GHS">GHS</option>
<option value="GIP">GIP</option>
<option value="GMD">GMD</option>
<option value="GNF">GNF</option>
<option value="GTQ">GTQ</option>
<option value="GYD">GYD</option>
<option value="HKD">HKD</option>
<option value="HNL">HNL</option>
<option value="HRK">HRK</option>
<option value="HTG">HTG</option>
<option value="HUF">HUF</option>
<option value="IDR">IDR</option>
<option value="ILS">ILS</option>
<option value="IMP">IMP</option>
<option value="INR">INR</option>
<option value="IQD">IQD</option>
<option value="IRR">IRR</option>
<option value="ISK">ISK</option>
<option value="JEP">JEP</option>
<option value="JMD">JMD</option>
<option value="JOD">JOD</option>
<option value="JPY">JPY</option>
<option value="KES">KES</option>
<option value="KGS">KGS</option>
<option value="KHR">KHR</option>
<option value="KMF">KMF</option>
<option value="KPW">KPW</option>
<option value="KRW">KRW</option>
<option value="KWD">KWD</option>
<option value="KYD">KYD</option>
<option value="KZT">KZT</option>
<option value="LAK">LAK</option>
<option value="LBP">LBP</option>
<option value="LKR">LKR</option>
<option value="LRD">LRD</option>
<option value="LSL">LSL</option>
<option value="LYD">LYD</option>
<option value="MAD">MAD</option>
<option value="MDL">MDL</option>
<option value="MGA">MGA</option>
<option value="MKD">MKD</option>
<option value="MMK">MMK</option>
<option value="MNT">MNT</option>
<option value="MOP">MOP</option>
<option value="MRU">MRU</option>
<option value="MUR">MUR</option>
<option value="MVR">MVR</option>
<option value="MWK">MWK</option>
<option value="MXN">MXN</option>
<option value="MYR">MYR</option>
<option value="MZN">MZN</option>
<option value="NAD">NAD</option>
<option value="NGN">NGN</option>
<option value="NIO">NIO</option>
<option value="NOK">NOK</option>
<option value="NPR">NPR</option>
<option value="NZD">NZD</option>
<option value="OMR">OMR</option>
<option value="PAB">PAB</option>
<option value="PEN">PEN</option>
<option value="PGK">PGK</option>
<option value="PHP">PHP</option>
<option value="PKR">PKR</option>
<option value="PLN">PLN</option>
<option value="PYG">PYG</option>
<option value="QAR">QAR</option>
<option value="RON">RON</option>
<option value="RSD">RSD</option>
<option value="RUB">RUB</option>
<option value="RWF">RWF</option>
<option value="SAR">SAR</option>
<option value="SBD">SBD</option>
<option value="SCR">SCR</option>
<option value="SDG">SDG</option>
<option value="SEK">SEK</option>
<option value="SGD">SGD</option>
<option value="SHP">SHP</option>
<option value="SLL">SLL</option>
<option value="SOS">SOS</option>
<option value="SPL">SPL</option>
<option value="SRD">SRD</option>
<option value="STN">STN</option>
<option value="SVC">SVC</option>
<option value="SYP">SYP</option>
<option value="SZL">SZL</option>
<option value="THB">THB</option>
<option value="TJS">TJS</option>
<option value="TMT">TMT</option>
<option value="TND">TND</option>
<option value="TOP">TOP</option>
<option value="TRY">TRY</option>
<option value="TTD">TTD</option>
<option value="TVD">TVD</option>
<option value="TWD">TWD</option>
<option value="TZS">TZS</option>
<option value="UAH">UAH</option>
<option value="UGX">UGX</option>
<option value="UYU">UYU</option>
<option value="UZS">UZS</option>
<option value="VEF">VEF</option>
<option value="VND">VND</option>
<option value="VUV">VUV</option>
<option value="WST">WST</option>
<option value="XAF">XAF</option>
<option value="XCD">XCD</option>
<option value="XDR">XDR</option>
<option value="XOF">XOF</option>
<option value="XPF">XPF</option>
<option value="YER">YER</option>
<option value="ZAR">ZAR</option>
<option value="ZMW">ZMW</option>
<option value="ZWD">ZWD</option>

app/views/piggy_banks/_piggy_bank_details.html.erb
<div class="row">
  <div class="col-xl-5">
    <h5 class="card-title"><%= piggy_bank.name %></h5>
    <h6 class="card-subtitle mb-2 text-muted"><%= piggy_bank.description %></h6>
  </div>
  <div class="col-xl-7">
      <div class="row">
        <div class="col-md-3 text-nowrap small">
          <%= piggy_bank.currency %>
        </div>
        <div class="col-md-9 text-right">
          <h1><%= number_to_currency piggy_bank.balance %></h1>
        </div>
      </div>

      <div class="row">
        <div class="col-md-6 small">
          <div class="row">
            <div class="col-md-12">
              <%= t '.total_credits' %>
            </div>
          </div>
          <div class="row">
            <div class="col-md-4 text-nowrap small">
              <%= piggy_bank.currency %>
            </div>
            <div class="col-md-8 text-right">
              <h6><%= number_to_currency piggy_bank.total_credit %></h6>
            </div>
          </div>
        </div>
        <div class="col-md-6 small">
          <div class="row">
            <div class="col-md-12">
              <%= t '.total_debits' %>
            </div>
          </div>
          <div class="row">
            <div class="col-md-4 text-nowrap small">
              <%= piggy_bank.currency %>
            </div>
            <div class="col-md-8 text-right">
              <h6><%= number_to_currency piggy_bank.total_debit %><h6>
            </div>
          </div>
        </div>
      </div>
  </div>
</div>

app/views/piggy_banks/edit.html.erb
<div class="container mt-5">
  <div class="row">
    <div class="col-md-6">
        <h3><b><%= t('.editing') %> <%= @piggy_bank.name %></b></h3>
    </div>
  </div>
</div>

<div class="container">
  <div class="row">
    <div class="col-md-6">
      <hr />
      <h5 class="mb-4"><%= t '.actual_piggy_bank' %></h5>
      <div class="card shadow">
        <div class="card-body">
          <%= render partial: "piggy_banks/piggy_bank_details", locals: { piggy_bank: @piggy_bank } %>
        </div>
      </div>
    </div>

    <div class="col-md-6">
      <hr />
      <h5 class="mb-4"><%= t '.updating_piggy_bank' %></h5>
      <div class="card shadow">
        <div class="card-body">
          <%= form_with scope: :piggy_bank, url: "/piggy_banks/#{@piggy_bank.id}", method: :put do |form| %>
            <div class="form-group">
              <%= form.text_field :name, class: "form-control", placeholder: t('.name'), required: true %>
            </div>
            <div class="form-group">
              <%= form.text_field :description, class: "form-control", placeholder: t('.description'), required: true  %>
            </div>
            <div class="form-group">
              <select name="piggy_bank[currency]" id="piggy_bank_currency" required=true class="custom-select">
                <%= render partial: "piggy_banks/currencies" %>
              </select>
            </div>
            <%= form.submit t('.update_piggy_bank'), class: "btn btn-primary btn-block" %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/piggy_banks/index.html.erb
<div class="container mt-5">
  <div class="row">
    <div class="col-md-9 mb-2">
        <h3><%= t '.my_piggy_banks' %></h3>
    </div>
    <div class="col-md-3 text-right">
      <%= link_to t('.new_piggy_bank'), new_piggy_bank_path, class: "btn btn-primary btn-block right shadow-sm" unless @piggy_banks.blank? %>
    </div>
  </div>
</div>

<div class="container mt-4">
  <% if @piggy_banks.blank? %>
  <div class="card mb-4 shadow">
    <div class="card-body text-secondary d-flex">
      <div class="row">
        <div class="col-sm-4 flex-row align-self-center text-center">
          <%= image_tag "dollar-glass.gif", class: "fill-width" %>
        </div>
        <div class="col-sm-8 flex-row align-self-center text-center">
          <p><%= t '.warn_1' %></p>
          <p><%= t '.warn_2' %></p>
          <br />
          <%= link_to t('.create_piggy_bank'), new_piggy_bank_path, class: "btn btn-primary" %>
        </div>
      </div>
    </div>
  </div>
  <% else %>
    <div class="row">
      <% @piggy_banks.each do |piggy_bank| %>
        <div class="col-md-6">
          <div class="card mb-4 shadow">
            <div class="card-body">
              <%= link_to piggy_bank_movements_path(piggy_bank.id), class: "card-body-link" do %>
               <%= render partial: "piggy_banks/piggy_bank_details", locals: { piggy_bank: piggy_bank } %>
              <% end %>
            </div>
            <div class="card-footer text-muted">
              <%= link_to t('.movement'), piggy_bank_movements_path(piggy_bank.id), class: "card-link" %>
              <%= link_to t('.edit'), edit_piggy_bank_path(piggy_bank), class: "card-link" %>
              <%= link_to t('.destroy'), piggy_bank_path(piggy_bank), method: :delete, data: { confirm: "Destroy piggy bank #{piggy_bank.name}?" }, class: "card-link"%>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  <% end %>

</div>